include:
  - project: 'warmichi/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    HCLOUD_TOKEN_FILE:
      vault: infra/prod/hetzner/HCLOUD_TOKEN@secret
    HCLOUD_SSH_KUBEONE_PRIVATE_KEY_FILE:
      vault: infra/prod/hetzner/HCLOUD_SSH_KUBEONE_PRIVATE_KEY@secret
    HCLOUD_SSH_KUBEONE_PUBLIC_KEY_FILE:
      vault: infra/prod/hetzner/HCLOUD_SSH_KUBEONE_PUBLIC_KEY@secret
     
before_script:
  - export HCLOUD_TOKEN=$(cat $HCLOUD_TOKEN_FILE)
  - export TF_VAR_HCLOUD_SSH_KUBEONE_PRIVATE_KEY=$(cat $HCLOUD_SSH_KUBEONE_PRIVATE_KEY_FILE)
  - export TF_VAR_HCLOUD_SSH_KUBEONE_PUBLIC_KEY=$(cat $HCLOUD_SSH_KUBEONE_PUBLIC_KEY_FILE)

validate:
  stage: validate
  extends: .secrets