include:
  - project: 'warmichi/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    HCLOUD_TOKEN_FILE:
      vault: infra/prod/hetzner/HCLOUD_TOKEN@secret
    HCLOUD_SSH_KUBEONE_PRIVATE_KEY_FILE:
      vault: infra/prod/hetzner/HCLOUD_SSH_KUBEONE_PRIVATE_KEY@secret
    HCLOUD_SSH_KUBEONE_PUBLIC_KEY_FILE:
      vault: infra/prod/hetzner/HCLOUD_SSH_KUBEONE_PUBLIC_KEY@secret
     
before_script:
  - export HCLOUD_TOKEN=$(cat $HCLOUD_TOKEN_FILE)
  - export TF_VAR_HCLOUD_SSH_KUBEONE_PRIVATE_KEY=$(cat $HCLOUD_SSH_KUBEONE_PRIVATE_KEY_FILE)
  - export TF_VAR_HCLOUD_SSH_KUBEONE_PUBLIC_KEY=$(cat $HCLOUD_SSH_KUBEONE_PUBLIC_KEY_FILE)

.install-curl-jq: &install-curl-jq
  - apk add --update curl jq
  - alias convert_report="jq -r '([.resource_changes[].change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"

.gitlab-tf-backend: &gitlab-tf-backend
  - export TF_ADDRESS=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/production
  - export TF_HTTP_ADDRESS=${TF_ADDRESS}
  - export TF_HTTP_LOCK_ADDRESS=${TF_ADDRESS}/lock
  - export TF_HTTP_LOCK_METHOD=POST
  - export TF_HTTP_UNLOCK_ADDRESS=${TF_ADDRESS}/lock
  - export TF_HTTP_UNLOCK_METHOD=DELETE
  - export TF_HTTP_USERNAME=gitlab-ci-token
  - export TF_HTTP_PASSWORD=${CI_JOB_TOKEN}
  - export TF_HTTP_RETRY_WAIT_MIN=5
  - echo "Using HTTP Backend at $TF_HTTP_ADDRESS"
  - terraform --version
  - terraform init -reconfigure

stages:
  - validate
  - plan
  - apply
  - kubeone
  - deploy
  - destroy-apps
  - destroy

validate:
  stage: validate
  extends: .secrets

apply:
  stage: apply
  extends: .secrets
  script:
    - *install-curl-jq
    - *gitlab-tf-backend
    - terraform apply -auto-approve
    - DYNAMIC_ENVIRONMENT_URL=$(terraform output -no-color env-dynamic-url)
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env
    - terraform output -json > output.json
  artifacts:
    paths:
    - output.json

kubeone:
  image:
    name: archlinux:latest
  stage: kubeone
  extends: .secrets
  script:
    - pacman -Sy kubeone --noconfirm
    - kubeone apply --manifest $KUBEONE_CONFIG --tfjson output.json