include:
  - project: 'warmichi/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    HCLOUD_TOKEN_FILE:
      vault: admin/infra/prod/hetzner/HCLOUD_TOKEN@secret
      
before_script:
  - if ["$HCLOUD_TOKEN" != null]; then export HCLOUD_TOKEN=$(cat $HCLOUD_TOKEN_FILE); fi

validate:
  stage: validate
  extends: .secrets
  script:
    - echo 
