include:
  - project: 'warmichi/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    HCLOUD_TOKEN_FILE:
      vault: infra/prod/hetzner/HCLOUD_TOKEN@secret
      
before_script:
  - export HCLOUD_TOKEN=$(cat $HCLOUD_TOKEN_FILE)
